#!/bin/sh

PORT=8080

bb(){
    which busybox > /dev/null && echo "httpd running on port $PORT..."
    busybox httpd -f -p $PORT
}

py3(){
    python3 -m http.server $PORT
}

py(){
    if [ "`python -c 'import sys; print(sys.version_info[:])[0]'`" == "3" ]; then
        python3 -m http.server $PORT
    else
        py3
    fi
}

rb(){
    ruby -run -ehttpd . -p$PORT
}

bb || py3 || py || rb || "Error: No suitable interpreter available"
